export const FETCH_RECORDINGS_BY_PAYLOAD_REQUEST = 'FETCH_MEETINGS_BY_PAYLOAD_REQUEST' as const;
export const FETCH_RECORDINGS_BY_PAYLOAD_SUCCESS = 'FETCH_RECORDINGS_BY_PAYLOAD_SUCCESS' as const;
export const FETCH_RECORDINGS_BY_PAYLOAD_FAILURE = 'FETCH_RECORDINGS_BY_PAYLOAD_FAILURE' as const;
export const FETCH_RECORDING_REQUEST = 'FETCH_RECORDING_REQUEST' as const;
export const FETCH_RECORDING_SUCCESS = 'FETCH_RECORDING_SUCCESS' as const;
export const FETCH_RECORDING_FAILURE = 'FETCH_RECORDING_FAILURE' as const;
