export const FETCH_PRESET_REQUEST = 'FETCH_PRESET_REQUEST' as const;
export const FETCH_PRESET_SUCCESS = 'FETCH_PRESET_SUCCESS' as const;
export const FETCH_PRESET_FAILURE = 'FETCH_PRESET_FAILURE' as const;

export const SET_PRESET_REQUEST = 'SET_PRESET_REQUEST' as const;
export const SET_PRESET_SUCCESS = 'SET_PRESET_SUCCESS' as const;
export const SET_PRESET_FAILURE = 'SET_PRESET_FAILURE' as const;

export const GET_PRESET_REQUEST = 'GET_PRESET_REQUEST' as const;
export const GET_PRESET_SUCCESS = 'GET_PRESET_SUCCESS' as const;
export const GET_PRESET_FAILURE = 'GET_PRESET_FAILURE' as const;
