export const FETCH_CLIENT_MEETING_REQUEST = 'FETCH_CLIENT_MEETING_REQUEST' as const;
export const FETCH_CLIENT_MEETING_SUCCESS = 'FETCH_CLIENT_MEETING_SUCCESS' as const;
export const FETCH_CLIENT_MEETING_FAILURE = 'FETCH_CLIENT_MEETING_FAILURE' as const;
